name: CI
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Python tests
        uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: python -m venv .venv && . .venv/bin/activate && pip install -U pip pytest psycopg2 && pytest -q tests/python
        shell: bash

      - name: Node tests
        uses: actions/setup-node@v4
        with: { node-version: "20" }
      - run: npm i -g pnpm && pnpm i && pnpm test
        shell: bash
