name: Route Compliance
on:
  pull_request:
    types: [opened, edited, synchronize, ready_for_review, reopened]
jobs:
  route:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Detect paths
        id: filter
        uses: dorny/paths-filter@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: |
            code:
              - 'src/**'
              - 'api/**'
              - 'migrations/**'
            docs_plan:
              - 'docs/BUILD_PLAN.md'
              - 'docs/TEST_MATRIX.md'
              - 'docs/API_SURFACE.md'
              - 'docs/DB_SCHEMA.sql'
            todo:
              - 'docs/TODO.md'

      - name: Enforce plan/docs updates when code changes
        if: steps.filter.outputs.code == 'true'
        run: |
          changed_plan="${{ steps.filter.outputs.docs_plan }}"
          changed_todo="${{ steps.filter.outputs.todo }}"
          if [ "$changed_plan" != "true" ]; then
            echo "::error::Code changed but planning docs were not updated (docs/BUILD_PLAN.md, TEST_MATRIX.md, API_SURFACE.md, DB_SCHEMA.sql)."
            exit 1
          fi
          if [ "$changed_todo" != "true" ]; then
            echo "::error::Code changed but docs/TODO.md was not updated."
            exit 1
          fi
